sonar.projectKey=Tugas-Besar-MKEPL-Kelompok-RCR
sonar.projectName=KalkulatorGUI
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8
sonar.language=java
