# This workflow will build a Java project with Ant
# Testing Deployment

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: |
          New-Item -ItemType Directory -Force -Path out\classes
          javac -d out\classes src\Kalkulator\Kalkulator.java
       
      - name: Testing
        run: ant tests
      

      - name: Inspection
        run: ant checkstyle

      - name: Delivery
        run: |
          New-Item -ItemType Directory -Force -Path out\dist
          javac -d out\classes src\Kalkulator\Kalkulator.java
          jar cfe out\Kalkulator.jar Kalkulator.Kalkulator -C out\classes .
          jpackage --input out --dest out\dist --name KalkulatorGUI --main-jar Kalkulator.jar --main-class Kalkulator.Kalkulator --type exe --app-version 1.0 --vendor MKEPL

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KalkulatorGUI-exe
          path: out/dist/
