# This workflow will build a Java project with Ant
# Testing Deployment

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: ant compile

      - name: Testing
        run: ant tests

      - name: Inspection
        run: ant checkstyle

      - name: SonarQube Analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=Tugas-Besar-MKEPL-Kelompok-RCR
            -Dsonar.projectName=KalkulatorGUI
            -Dsonar.sources=src
            -Dsonar.java.binaries=build/classes
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Delivery
        run: |
          New-Item -ItemType Directory -Force -Path out\dist
          javac -d out\classes src\Kalkulator\Kalkulator.java
          jar cfe out\Kalkulator.jar Kalkulator.Kalkulator -C out\classes .
          jpackage --input out --dest out\dist --name KalkulatorGUI --main-jar Kalkulator.jar --main-class Kalkulator.Kalkulator --type exe --app-version 1.0 --vendor MKEPL

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KalkulatorGUI-exe
          path: out/dist/
